sudo: required
services: docker
language: bash
env:
    global:
        - QEMU_VER=v2.9.1
    matrix:
        - ARCH=amd64 INCLUDE=wget QEMU_ARCH=x86_64 SUITE=stretch UNAME_ARCH=x86_64 VERSION=stretch
        - ARCH=arm64 INCLUDE=wget QEMU_ARCH=aarch64 SUITE=stretch UNAME_ARCH=arm64 VERSION=stretch
        - ARCH=armhf INCLUDE=wget QEMU_ARCH=arm SUITE=stretch UNAME_ARCH=armv7l VERSION=stretch
        - ARCH=i386 INCLUDE=wget QEMU_ARCH=i386 SUITE=stretch UNAME_ARCH=i386 VERSION=stretch
        - ARCH=ppc64el INCLUDE=wget QEMU_ARCH=ppc64 SUITE=stretch UNAME_ARCH=ppc64el VERSION=stretch
        

before_script:
    - echo "deb http://ftp.de.debian.org/debian stretch main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553 7638D0442B90D010
    - sudo apt-get update -qq
    - sudo apt-get -y install debootstrap qemu-user-static
script:
    - sudo ./update.sh -a "$ARCH" -v "$VERSION" -q "$QEMU_ARCH" -u "$QEMU_VER" -d "$DOCKER_REPO" -s "$SUITE" -i "$INCLUDE" -o "$UNAME_ARCH"

after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_REPO; fi
    - echo "Downloading manifest-tool"
    - wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64
    - mv manifest-tool-linux-amd64 manifest-tool
    - chmod +x manifest-tool
    - ./manifest-tool
    - echo "Pushing manifest $DOCKER_REPO:latest"
    - ./manifest-tool --username $DOCKER_USERNAME -- password $DOCKER_PASSWORD push from-args \
      --platforms linux/amd64,linux/386,linux/arm,linux/arm64,linux/ppc64le \
      --template "$DOCKER_REPO:$ARCH-$VERSION" \
      --target "$DOCKER_REPO:latest"
